version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://35.78.221.49:8080
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8080:3000"
    