version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "8432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
  app_data:
    driver: local
  nginx:
    driver: local